name: Validate and Auto Publish

on:
  push:
    branches:
      - main
    paths:
      - index.html
  pull_request: {}

jobs:
  validate-and-publish:
    name: Validate and Publish
    runs-on: ubuntu-20.04 # only linux supported at present
    steps:
      - uses: actions/checkout@v3
      - uses: w3c/spec-prod@v2 # use the action
        with:
          GH_PAGES_BRANCH: gh-pages
          TOOLCHAIN: respec
          # W3C_ECHIDNA_TOKEN: ${{ secrets.ECHIDNA_TOKEN }}
          W3C_WG_DECISION_URL: "https://lists.w3.org/Archives/Public/public-webrtc/2016Mar/0031.html"
          # W3C_NOTIFICATIONS_CC: "nobody@w3.org"
          VALIDATE_LINKS: false

